name: style&tests

on: push

jobs:
  check-style:
    name: Lint code base
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Npm install
        run: npm install
      - name: Run make lint
        run: make lint
  testins:
    name: Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Npm install
        run: npm install
        env:
          CI: true
      - name: Test & publish code coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
